export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SCHEDULES = "FETCH_USER_SCHEDULES";
export const CREATE_SCHEDULE = "CREATE_SCHEDULE";
export const FETCH_SCHEDULE = "FETCH_SCHEDULE";
export const DELETE_SCHEDULE = "DELETE_SCHEDULE";
